version: '3'

services:
  apache: 
    build: .
    image: psycho-apache:latest
    container_name: psycho-apache
    volumes: 
      - .:/var/www/html/ 
    ports:
      - "8001:80"
    environment:
      - XDEBUG_ENABLED=true
